### PR TITLE
chore: update mkdirp to support strict mode

### PR DESCRIPTION
**Pull request by calebboyd**
Enables the library to run in environments where strict mode is enabled.

### CODE REVIEW

**Comment by calebboyd** [comment]
@steveukx LGTY?

**Comment by steveukx** [comment]
Apologies for the delay. Please can you remove the update to the version,
it's updated automatically as part of the deployment. Other than that, good
to go.

**Comment by calebboyd** [comment]
Done

**Comment by steveukx** [comment]
Available as 0.0.16 on npm now

**Comment by calebboyd** [comment]
Great! Thanks

**Pull request merged**
